version: "3.8"
services:
  reporter.svc:
    image: reporter:latest
    build:
      context: .
      dockerfile: Dockerfile.local
    restart: on-failure
    container_name: reporter
    ports:
      - "8080:8080"
    environment:
      REPORTER_DB_USERNAME: user
      REPORTER_DB_PASSWORD: password
      REPORTER_DB_URL: jdbc:postgresql://reporter_db.svc:5432/reporter_db
  db:
    image: postgres:alpine
    container_name: reporter_db
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: reporter_db
        PGDATA: /var/lib/postgresql/data/some_name/
    volumes:
      - ./src/test/resources/db/:/docker-entrypoint-initdb.d/
    networks:
      default:
        aliases:
          - reporter_db.svc
