version: "3.8"
services:
  reporter.svc:
    image: reporter:latest
    build:
      context: .
      dockerfile: Dockerfile.local
    restart: on-failure
    container_name: reporter
    ports:
      - "8080:8080"
  db:
    image: postgres:alpine
    container_name: reporter_db
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: reporter_db
    networks:
      default:
        aliases:
          - reporter_db.svc
