--CREATE DATABASE REPORTER_DB;

--USE REPORTER_DB;
DROP TABLE IF EXISTS MESSAGE;
CREATE TABLE MESSAGE (
    ID SERIAL PRIMARY KEY,
    SYMBOL VARCHAR(255),
    OVERALL_SENTIMENT_SCORE DOUBLE PRECISION,
    OVERALL_SENTIMENT_LABEL VARCHAR(255),
    MESSAGE_DATE TIMESTAMP
);

INSERT INTO MESSAGE (SYMBOL, OVERALL_SENTIMENT_SCORE, OVERALL_SENTIMENT_LABEL, MESSAGE_DATE)
VALUES ('AAPL', 0.5, 'POSITIVE', CURRENT_TIMESTAMP);