spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: Reporter
  datasource:
    url: ${REPORTER_DB_URL}
    username: ${REPORTER_DB_USERNAME}
    password: ${REPORTER_DB_PASSWORD}
  sql:
    init:
      mode: always
  jackson:
    serialization:
      INDENT_OUTPUT: true
